name = "zeptomail"
version = "0.1.0"

licences = ["Apache-2.0"]
description = "A wrapper for ZeptoMail's transactional email API"
repository = { type = "github", user = "lpil", repo = "zeptomail" }
links = [
  { title = "Website", href = "https://www.zoho.com/zeptomail/" },
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]

[dependencies]
gleam_stdlib = "~> 0.22"
gleam_json = "~> 0.5"
gleam_http = "~> 3.0"

[dev-dependencies]
gleeunit = "~> 0.6"
